In [1]:
import numpy as np
import pandas as pd


Date	            Transaction date

Store ID	        Unique identifier for each store

Product ID	        Unique identifier for each product

Category	        Product category (e.g., Electronics, Groceries, Furniture)

Region	            Store location or region

Inventory Level	    Available stock level at the store

Units Sold	        Number of units sold on the given date

Units Ordered	    Number of units ordered/replenished

Price	            Selling price of the product

Discount	        Discount applied to the product

Weather Condition	External weather condition affecting demand


Promotion	        Promotion indicator (e.g., 0 = No, 1 = Yes)

Competitor Pricing	Competitor price for similar products

Seasonality	        Seasonal pattern indicator (e.g., Holiday, Off-season)

Epidemic	        External disruption indicator (e.g., 0 = No, 1 = Yes)

Demand	            Target variable representing customer demand (units)

In [2]:
df = pd.read_csv('demand_forecasting.csv')
print(df.head())

         Date Store ID Product ID     Category Region  Inventory Level  \
0  2022-01-01     S001      P0001  Electronics  North              195
1  2022-01-01     S001      P0002     Clothing  North              117
2  2022-01-01     S001      P0003     Clothing  North              247
3  2022-01-01     S001      P0004  Electronics  North              139
4  2022-01-01     S001      P0005    Groceries  North              152

   Units Sold  Units Ordered  Price  Discount Weather Condition  Promotion  \
0         102            252  72.72         5             Snowy          0
1         117            249  80.16        15             Snowy          1
2         114            612  62.94        10             Snowy          1
3          45            102  87.63        10             Snowy          0
4          65            271  54.41         0             Snowy          0

   Competitor Pricing Seasonality  Epidemic  Demand
0               85.73      Winter         0     115
1               92.02      Winter         0     229
2               60.08      Winter         0     157
3               85.19      Winter         0      52
4               51.63      Winter         0      59

In [3]:
grouped = df.groupby('Store ID')['Region'].unique()
print(grouped)

Store ID
S001    [North]
S002    [South]
S003     [East]
S004     [West]
S005    [North]
Name: Region, dtype: object

In [4]:
df.drop('Region', axis=1, inplace=True)

In [5]:
grouped = df.groupby('Product ID')['Category'].unique()
print(grouped)

Product ID
P0001                       [Electronics, Groceries, Toys]
P0002             [Clothing, Toys, Groceries, Electronics]
P0003    [Clothing, Groceries, Electronics, Furniture, ...
P0004                             [Electronics, Groceries]
P0005             [Groceries, Electronics, Toys, Clothing]
P0006                          [Toys, Clothing, Groceries]
P0007                                    [Groceries, Toys]
P0008        [Electronics, Groceries, Clothing, Furniture]
P0009                                [Clothing, Groceries]
P0010                               [Furniture, Groceries]
P0011        [Furniture, Groceries, Electronics, Clothing]
P0012                  [Groceries, Electronics, Furniture]
P0013                                    [Toys, Groceries]
P0014                  [Groceries, Electronics, Furniture]
P0015               [Toys, Clothing, Groceries, Furniture]
P0016    [Groceries, Clothing, Electronics, Furniture, ...
P0017                          [Toys, Furniture, Clothing]
P0018                     [Groceries, Clothing, Furniture]
P0019                     [Furniture, Clothing, Groceries]
P0020                          [Furniture, Clothing, Toys]
Name: Category, dtype: object

In [6]:
df['Epidemic'].value_counts()/len(df)*100

Epidemic
0    80.0
1    20.0
Name: count, dtype: float64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  str
 1   Store ID            76000 non-null  str
 2   Product ID          76000 non-null  str
 3   Category            76000 non-null  str
 4   Inventory Level     76000 non-null  int64
 5   Units Sold          76000 non-null  int64
 6   Units Ordered       76000 non-null  int64
 7   Price               76000 non-null  float64
 8   Discount            76000 non-null  int64
 9   Weather Condition   76000 non-null  str
 10  Promotion           76000 non-null  int64
 11  Competitor Pricing  76000 non-null  float64
 12  Seasonality         76000 non-null  str
 13  Epidemic            76000 non-null  int64
 14  Demand              76000 non-null  int64
dtypes: float64(2), int64(7), str(6)
memory usage: 11.5 MB

In [8]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [9]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand
count,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000
mean,301.062842,88.827316,89.090645,67.726028,9.087039,0.328947,69.454029,0.200000,104.317158
std,226.510161,43.994525,162.404627,39.377899,7.475781,0.469834,40.943818,0.400003,46.964801
min,0.000000,0.000000,0.000000,4.740000,0.000000,0.000000,4.290000,0.000000,4.000000
25%,136.000000,58.000000,0.000000,31.997500,5.000000,0.000000,32.620000,0.000000,71.000000
50%,227.000000,84.000000,0.000000,64.500000,10.000000,0.000000,65.700000,0.000000,100.000000
75%,408.000000,114.000000,121.000000,95.830000,10.000000,1.000000,97.932500,0.000000,133.000000
max,2267.000000,426.000000,1616.000000,228.030000,25.000000,1.000000,261.220000,1.000000,430.000000

In [10]:
df['Store ID'].value_counts()/len(df)*100

Store ID
S001    20.0
S002    20.0
S003    20.0
S004    20.0
S005    20.0
Name: count, dtype: float64

In [11]:
df['Product ID'].value_counts()/len(df)*100

Product ID
P0001    5.0
P0002    5.0
P0003    5.0
P0004    5.0
P0005    5.0
P0006    5.0
P0007    5.0
P0008    5.0
P0009    5.0
P0010    5.0
P0011    5.0
P0012    5.0
P0013    5.0
P0014    5.0
P0015    5.0
P0016    5.0
P0017    5.0
P0018    5.0
P0019    5.0
P0020    5.0
Name: count, dtype: float64

In [12]:
df['Weather Condition'].value_counts()/len(df)*100

Weather Condition
Cloudy    32.052632
Sunny     30.236842
Rainy     23.026316
Snowy     14.684211
Name: count, dtype: float64

In [13]:
df['Seasonality'].value_counts()/len(df)*100

Seasonality
Winter    27.631579
Spring    24.210526
Summer    24.210526
Autumn    23.947368
Name: count, dtype: float64

In [14]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Inventory Level',
       'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition',
       'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand'],
      dtype='str')

In [15]:
df.head()

,Date,Store ID,Product ID,Category,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [16]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Inventory Level',
       'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition',
       'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand'],
      dtype='str')

Feature creation

In [17]:

df['Price_Premium_Index'] = df['Price'] / df['Competitor Pricing']
df['Discount_Depth'] = df['Discount'] / df['Price']

df['Date'] = pd.to_datetime(df['Date'])

df['Day_of_Week'] = df['Date'].dt.dayofweek
df['Is_Weekend']  = df['Date'].dt.dayofweek.isin([5, 6]).astype(int)
df['Month']       = df['Date'].dt.month
df['Day_of_Month']= df['Date'].dt.day

In [18]:
df = df.sort_values(by=['Store ID', 'Product ID', 'Date']).reset_index(drop=True)

In [19]:
df['demand_lag1'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(1)
df['demand_lag2'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(2)
df['demand_lag3'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(3)
df['demand_lag4'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(4)
df['demand_lag5'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(5)
df['demand_lag6'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(6)
df['demand_lag7'] = df.groupby(['Store ID', 'Product ID'])['Demand'].shift(7)
df['Units Sold_lag1'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(1)
df['Units Sold_lag2'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(2)
df['Units Sold_lag3'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(3)
df['Units Sold_lag4'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(4)
df['Units Sold_lag5'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(5)
df['Units Sold_lag6'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(6)
df['Units Sold_lag7'] = df.groupby(['Store ID', 'Product ID'])['Units Sold'].shift(7)

df['Units Ordered'] = df.groupby(['Store ID', 'Product ID'])['Units Ordered'].shift(1)

In [20]:
df.dropna(inplace=True)
df.set_index('Date', inplace=True)
df.head()

,Store ID,Product ID,Category,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,...,demand_lag5,demand_lag6,demand_lag7,Units Sold_lag1,Units Sold_lag2,Units Sold_lag3,Units Sold_lag4,Units Sold_lag5,Units Sold_lag6,Units Sold_lag7
Date,,,,,,,,,,,,,,,,,,,,,
2022-01-08,S001,P0001,Electronics,308,96,0.0,68.56,10,Snowy,1,...,132.0,84.0,115.0,92.0,98.0,129.0,42.0,142.0,71.0,102.0
2022-01-09,S001,P0001,Electronics,212,57,248.0,62.76,10,Sunny,0,...,67.0,132.0,84.0,96.0,92.0,98.0,129.0,42.0,142.0,71.0
2022-01-10,S001,P0001,Electronics,403,88,0.0,68.99,5,Cloudy,0,...,110.0,67.0,132.0,57.0,96.0,92.0,98.0,129.0,42.0,142.0
2022-01-11,S001,P0001,Electronics,315,112,0.0,73.71,0,Cloudy,0,...,146.0,110.0,67.0,88.0,57.0,96.0,92.0,98.0,129.0,42.0
2022-01-12,S001,P0001,Electronics,203,70,0.0,65.76,10,Snowy,0,...,87.0,146.0,110.0,112.0,88.0,57.0,96.0,92.0,98.0,129.0

In [21]:
df.to_csv('preprocessed.csv')